# Generated by Django 3.2.5 on 2021-07-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
