# Generated by Django 3.2.5 on 2021-07-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_auto_20210723_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_work_company',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_work_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
