# Generated by Django 3.2.5 on 2021-07-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0004_auto_20210723_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cgpa',
            field=models.FloatField(default=5),
        ),
    ]
